server:
  port: 10000

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/cloud_auth}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect